INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (0, 'Portatil 15.6" Sony Vaio');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (1, 'Disco Duro 500GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (2, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (3, 'Monitor Asus A28');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (4, 'NVIDIA GeForce 9600GT');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (5, 'Cable HDMI');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (6, 'Monitor Asus A24');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (7, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (8, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (9, 'Monitor Sony LCD 22"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (10, 'Monitor Asus A32');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (11, 'Samsung Galaxy S4');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (12, 'Impresora Laser Brother BX1');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (13, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (14, 'LG Optimus Black Negro');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (15, 'Pendrive Kingston 4GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (16, 'Monitor Asus A22');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (17, 'Monitor Asus A32');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (18, 'LG Optimus Black Negro');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (19, 'Disco Duro 640GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (20, 'Impresora Multifuncion Canon Pixma P255');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (21, 'Monitor Sony LCD 22"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (22, 'NVIDIA GeForce 9600');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (23, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (24, 'NVIDIA GeForce 9500');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (25, 'Apple Iphone 4GS');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (26, '');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (27, 'Cable USB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (28, 'Monitor Asus A22');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (29, 'Pendrive Kingston 16GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (30, 'Pendrive Kingston 8GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (31, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (32, 'Disco Duro 500GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (33, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (34, 'Cable HDMI');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (35, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (36, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (37, 'Monitor Sony LED 23.6"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (38, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (39, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (40, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (41, 'Monitor Asus A22');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (42, 'Impresora Laser Brother BX1');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (43, 'NVIDIA GeForce 9600');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (44, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (45, 'Monitor Asus A28');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (46, 'NVIDIA GeForce 9600GT');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (47, 'Monitor Sony LCD 22"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (48, 'Apple Ipod Touch 4G');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (49, 'Monitor Asus A24');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (50, 'NVIDIA GeForce 9600');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (51, 'Monitor Sony LED 23.6"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (52, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (53, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (54, 'Cable Ethernet');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (55, 'Monitor Asus A28');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (56, 'Pendrive Kingston 8GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (57, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (58, 'NVIDIA GeForce 9600');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (59, 'Monitor Asus A23');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (60, 'Cable Ethernet');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (61, 'NVIDIA GeForce 9500');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (62, 'Disco Duro 640GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (63, 'Cable USB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (64, 'Monitor Asus A23');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (65, 'Cable USB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (66, 'Pendrive Kingston 4GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (67, 'Cable HDMI');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (68, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (69, 'Apple Iphone 4GS');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (70, '');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (71, 'Impresora Laser Brother BX1');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (72, 'Disco Duro 640GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (73, 'NVIDIA GeForce 9600GT');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (74, 'Cable Ethernet');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (75, 'Monitor Asus A22');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (76, '');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (77, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (78, 'LG Optimus Black Negro');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (79, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (80, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (81, 'Monitor Asus A23');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (82, 'Monitor Asus A22');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (83, '');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (84, 'Monitor Sony LED 23.6"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (85, 'Monitor Sony LED 23.6"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (86, 'Monitor Asus A23');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (87, 'Portatil 15.6" Sony Vaio');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (88, 'NVIDIA GeForce 9600GT');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (89, 'Apple Iphone 4GS');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (90, 'Apple Ipod Touch 4G');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (91, 'Apple MacBook Pro 13"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (92, 'Monitor Sony LCD 22"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (93, 'Samsung Galaxy S4');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (94, 'Pendrive Kingston 4GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (95, 'Lavadora Zanussi Z300');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (96, 'Disco Duro SSD 128GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (97, 'Pendrive Kingston 4GB');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (98, 'Samsung Galaxy Tab 7"');
INSERT INTO PRODUCTO(id_producto, nombre, descripcion) VALUES (99, 'Samsung Galaxy S4');
